/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import esper.Config;
import eu.hansolo.lightbulb.LightBulb;
import eu.hansolo.steelseries.gauges.Clock;
import eu.hansolo.steelseries.gauges.DigitalRadial;
import eu.hansolo.steelseries.gauges.DisplayCircular;
import eu.hansolo.steelseries.gauges.DisplaySingle;
import eu.hansolo.steelseries.gauges.Radial1Lcd;
import eu.hansolo.steelseries.gauges.Radial2Lcd;
import eu.hansolo.steelseries.gauges.Radial4;
import events.AccelerateEvent;
import events.BrakeEvent;
import events.Cruise_state_reading;
import events.EngineEvent;
import events.Gear_Reading;
import events.PerformEvent;
import events.RpmEvent;
import events.SpeedOMeterReading;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import model.AutoMobileManagmentSystem;

/**
 *
 * @author sam
 */
public class View_AMS extends javax.swing.JFrame {

    /**
     * Creates new form View_AMS
     */
    static int  speed = 0;
    static double RPM = 0.0;
    static int GearState = 1;
    static boolean enginestate = false;

    public View_AMS() {
        initComponents();

    }

    public DisplayCircular getDriveshaft_display() {
        return driveshaft_display;
    }

    public void setDriveshaft_display(DisplayCircular driveshaft_display) {
        this.driveshaft_display = driveshaft_display;
    }

    public JButton getButonStopTrip() {
        return butonStopTrip;
    }

    public JToggleButton getButtonAccelerate() {
        return buttonAccelerate;
    }

    public JButton getButtonBrake() {
        return buttonBrake;
    }

    public JButton getButtonFirstGear() {
        return buttonFirstGear;
    }

    public JButton getButtonSecondGear() {
        return buttonSecondGear;
    }

    public JButton getButtonSetFuel() {
        return buttonSetFuel;
    }

    public JToggleButton getButtonStartCruise() {
        return buttonStartCruise;
    }

    public JTextArea getScreen() {
        return screen;
    }

    public JButton getButtonStartEngine() {
        return buttonStartEngine;
    }

    public JButton getButtonStartTrip() {
        return buttonStartTrip;
    }

    public JButton getButtonStopCruise() {
        return buttonStopCruise;
    }

    public JButton getButtonStopEngine() {
        return buttonStopEngine;
    }

    public JButton getButtonThirdGear() {
        return buttonThirdGear;
    }

    public Clock getClock1() {
        return clock1;
    }

    public DigitalRadial getDigitalRadial1() {
        return digitalRadial1;
    }

    public DisplaySingle getDisplayAvgFuel() {
        return displayAvgFuel;
    }

    public DisplaySingle getDisplayCrusingSpeed() {
        return displayCrusingSpeed;
    }

    public DisplaySingle getDisplayGear() {
        return displayGear;
    }

    public DisplaySingle getDisplayMaintenance() {
        return displayMaintenance;
    }

    public DisplaySingle getDisplayMilesDriven() {
        return displayMilesDriven;
    }

    public DisplaySingle getDisplayRPM() {
        return displayRPM;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JLabel getjLabel6() {
        return jLabel6;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTextArea getjTextArea1() {
        return screen;
    }

    public LightBulb getLightBulb1() {
        return lightBulb1;
    }

    public Radial1Lcd getRadialFuel() {
        return radialFuel;
    }

    public Radial4 getRadialRPM() {
        return radialRPM;
    }

    public Radial2Lcd getRadialSpeedometer() {
        return radialSpeedometer;
    }

    public JSlider getSliderFuel() {
        return sliderFuel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        linear1 = new org.pushingpixels.trident.ease.Linear();
        clock1 = new eu.hansolo.steelseries.gauges.Clock();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        screen = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        buttonStartCruise = new javax.swing.JToggleButton();
        buttonStopCruise = new javax.swing.JButton();
        lightBulb1 = new eu.hansolo.lightbulb.LightBulb();
        buttonStartEngine = new javax.swing.JButton();
        buttonStopEngine = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        sliderFuel = new javax.swing.JSlider();
        buttonSetFuel = new javax.swing.JButton();
        buttonAccelerate = new javax.swing.JToggleButton();
        buttonBrake = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonFirstGear = new javax.swing.JButton();
        buttonSecondGear = new javax.swing.JButton();
        buttonThirdGear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        clibirate_lightBulb = new eu.hansolo.lightbulb.LightBulb();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lightBulb3 = new eu.hansolo.lightbulb.LightBulb();
        crusing_lightBulb1 = new eu.hansolo.lightbulb.LightBulb();
        radialFuel = new eu.hansolo.steelseries.gauges.Radial1Lcd();
        radialRPM = new eu.hansolo.steelseries.gauges.Radial4();
        displayCrusingSpeed = new eu.hansolo.steelseries.gauges.DisplaySingle();
        digitalRadial1 = new eu.hansolo.steelseries.gauges.DigitalRadial();
        displayGear = new eu.hansolo.steelseries.gauges.DisplaySingle();
        displayRPM = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel2 = new javax.swing.JLabel();
        displayAvgFuel = new eu.hansolo.steelseries.gauges.DisplaySingle();
        radialSpeedometer = new eu.hansolo.steelseries.gauges.Radial2Lcd();
        displayMilesDriven = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel8 = new javax.swing.JLabel();
        displayMaintenance = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        driveshaft_display = new eu.hansolo.steelseries.gauges.DisplayCircular();
        buttonStartTrip = new javax.swing.JButton();
        butonStopTrip = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tripbulb = new eu.hansolo.lightbulb.LightBulb();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automobile Management System");
        setBackground(new java.awt.Color(153, 153, 153));

        clock1.setBackgroundColor(eu.hansolo.steelseries.tools.BackgroundColor.LIGHT_GRAY);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        screen.setColumns(20);
        screen.setRows(5);
        jScrollPane1.setViewportView(screen);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Monitor");

        buttonStartCruise.setText("Start Cruising");
        buttonStartCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartCruiseActionPerformed(evt);
            }
        });

        buttonStopCruise.setText("Stop Cruising");
        buttonStopCruise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopCruiseActionPerformed(evt);
            }
        });

        buttonStartEngine.setText("Start Engine");
        buttonStartEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartEngineActionPerformed(evt);
            }
        });

        buttonStopEngine.setText("Stop Engine");
        buttonStopEngine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopEngineActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Set Fuel:");

        sliderFuel.setMaximum(10);
        sliderFuel.setValue(0);

        buttonSetFuel.setText("Set Fuel");
        buttonSetFuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetFuelActionPerformed(evt);
            }
        });

        buttonAccelerate.setText("Accelerate");
        buttonAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAccelerateActionPerformed(evt);
            }
        });

        buttonBrake.setText("Brake");
        buttonBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBrakeActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Low Gear");

        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Medium Gear");

        jLabel7.setForeground(new java.awt.Color(153, 255, 0));
        jLabel7.setText("Top Gear");

        buttonFirstGear.setText("First");
        buttonFirstGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFirstGearActionPerformed(evt);
            }
        });

        buttonSecondGear.setText("Second");
        buttonSecondGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSecondGearActionPerformed(evt);
            }
        });

        buttonThirdGear.setText("Third");
        buttonThirdGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThirdGearActionPerformed(evt);
            }
        });

        jButton1.setText("Start calibirate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Stop calibirate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonStartEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(buttonStopEngine, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lightBulb1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(buttonAccelerate)
                                    .addComponent(buttonBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buttonStartCruise)
                                            .addComponent(buttonStopCruise, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(crusing_lightBulb1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(sliderFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(buttonSetFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonSecondGear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(41, 41, 41)
                                                .addComponent(buttonThirdGear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(40, 40, 40)
                                                .addComponent(buttonFirstGear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lightBulb3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(211, 211, 211))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clibirate_lightBulb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lightBulb1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonStartEngine)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonStopEngine)))
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(buttonSetFuel)
                                            .addComponent(sliderFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(buttonStartCruise)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(buttonStopCruise))
                                    .addComponent(crusing_lightBulb1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAccelerate)
                                .addGap(27, 27, 27)
                                .addComponent(buttonBrake))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(buttonFirstGear))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(buttonSecondGear))
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(buttonThirdGear)
                                    .addComponent(jLabel7)))
                            .addComponent(lightBulb3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(clibirate_lightBulb, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );

        radialFuel.setMaxValue(10.0);
        radialFuel.setName("Fuel"); // NOI18N
        radialFuel.setTitle("Fuel");
        radialFuel.setTrackRange(10.0);
        radialFuel.setTrackSection(5.0);
        radialFuel.setTrackStartColor(new java.awt.Color(255, 0, 0));
        radialFuel.setTrackStopColor(new java.awt.Color(0, 255, 0));
        radialFuel.setTrackVisible(true);
        radialFuel.setUnitString("E/F");

        radialRPM.setToolTipText("");
        radialRPM.setMaxMeasuredValueVisible(true);
        radialRPM.setMaxValue(80.0);
        radialRPM.setTitle("RPM");
        radialRPM.setTrackRange(10.0);
        radialRPM.setTrackStart(70.0);
        radialRPM.setTrackStartColor(new java.awt.Color(255, 255, 0));
        radialRPM.setTrackVisible(true);
        radialRPM.setUnitString("X100");

        displayCrusingSpeed.setUnitString("Km/h");

        digitalRadial1.setTitle("Maintenance");
        digitalRadial1.setUnitString("Time");

        displayGear.setLcdColor(eu.hansolo.steelseries.tools.LcdColor.BLACK_LCD);
        displayGear.setLcdDecimals(0);
        displayGear.setUnitString("Gear");
        displayGear.setVerifyInputWhenFocusTarget(false);

        displayRPM.setUnitString("RPM");

        jLabel2.setText("Cruising Speed");

        displayAvgFuel.setUnitString("avg/fuel");
        displayAvgFuel.setVerifyInputWhenFocusTarget(false);

        radialSpeedometer.setLcdUnitStringVisible(true);
        radialSpeedometer.setTitle("Speed");
        radialSpeedometer.setUnitString("km.h");

        displayMilesDriven.setUnitString("Miles");

        jLabel8.setText("Miles Driven:");

        jLabel9.setText("Current Maintenance");

        jLabel10.setText("Average Speed");

        driveshaft_display.setAutoscrolls(true);
        driveshaft_display.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        driveshaft_display.setUnitString("SRPM");

        buttonStartTrip.setText("Start Trip");
        buttonStartTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartTripActionPerformed(evt);
            }
        });

        butonStopTrip.setText("Stop Trip");
        butonStopTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonStopTripActionPerformed(evt);
            }
        });

        jLabel3.setText("Drive shaft");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayRPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(displayCrusingSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(displayMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(displayMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonStartTrip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butonStopTrip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(radialRPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(radialSpeedometer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(displayAvgFuel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tripbulb, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radialFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(digitalRadial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(driveshaft_display, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(63, 63, 63))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(radialRPM, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                        .addComponent(digitalRadial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clock1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radialFuel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radialSpeedometer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(driveshaft_display, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(displayRPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(displayAvgFuel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                    .addComponent(displayMaintenance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(displayCrusingSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(displayMilesDriven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tripbulb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(buttonStartTrip)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(butonStopTrip))))
                        .addGap(29, 29, 29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartCruiseActionPerformed
        Config.sendEvent(new Cruise_state_reading(true));

    }//GEN-LAST:event_buttonStartCruiseActionPerformed

    private void buttonStopCruiseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopCruiseActionPerformed
        Config.sendEvent(new Cruise_state_reading(false));

    }//GEN-LAST:event_buttonStopCruiseActionPerformed

    private void buttonStartEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartEngineActionPerformed

        Config.sendEvent(new EngineEvent(true));

        //else do nothing.
    }//GEN-LAST:event_buttonStartEngineActionPerformed

    private void buttonStopEngineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopEngineActionPerformed

        Config.sendEvent(new EngineEvent((false)));
        //else do nothing.
    }//GEN-LAST:event_buttonStopEngineActionPerformed

    private void buttonSetFuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetFuelActionPerformed
        radialFuel.setValueAnimated(sliderFuel.getValue());

    }//GEN-LAST:event_buttonSetFuelActionPerformed

    public static double getSpeed() {
        return speed;
    }

    public static void setSpeed(int speed) {
        View_AMS.speed = speed;
    }

    public static double getRPM() {
        return RPM;
    }

    public static void setRPM(double RPM) {
        View_AMS.RPM = RPM;
    }

    public static double getGearState() {
        return GearState;
    }

    public static void setGearState(int GearState) {
        View_AMS.GearState = GearState;
    }

    public static boolean isEnginestate() {
        return enginestate;
    }

    public static void setEnginestate(boolean enginestate) {
        View_AMS.enginestate = enginestate;
    }

    public DisplayCircular getDisplaytime() {
        return driveshaft_display;
    }

    public void setDisplaytime(DisplayCircular displaytime) {
        this.driveshaft_display = displaytime;
    }

    private void buttonAccelerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAccelerateActionPerformed
       System.out.println("lldjfnefneffn");
       /* speed = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, true)[0];
        RPM = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, true)[1];
        GearState = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, true)[2];
        radialSpeedometer.setValueAnimated(speed);
        displayCrusingSpeed.setValueAnimated(speed);
        if (enginestate == true) {
            radialRPM.setValueAnimated(RPM);
            displayRPM.setValueAnimated(RPM);
        }*/
        //displayGear.setValueAnimated(GearState);
        
       Config.sendEvent(new AccelerateEvent((true)));
       Config.sendEvent(new SpeedOMeterReading((speed)));
       Config.sendEvent(new Gear_Reading((GearState)));
       Config.sendEvent(new RpmEvent((RPM)));
       Config.sendEvent(new PerformEvent(true));

    }//GEN-LAST:event_buttonAccelerateActionPerformed

    private void buttonBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBrakeActionPerformed
       /* speed = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, false)[0];
        RPM = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, false)[1];
        GearState = esper.Main.ams.PerformAcceleration(speed, GearState, RPM, false)[2];
        displayCrusingSpeed.setValueAnimated(speed);
        radialSpeedometer.setValueAnimated(speed);

        if (enginestate == true) {
            radialRPM.setValueAnimated(RPM);
            displayRPM.setValueAnimated(RPM);
        }
        displayGear.setValueAnimated(GearState);*/
        System.out.println("ll");
         Config.sendEvent(new BrakeEvent((false)));
       Config.sendEvent(new SpeedOMeterReading((speed)));
       Config.sendEvent(new Gear_Reading((GearState)));
       Config.sendEvent(new RpmEvent((RPM)));
       Config.sendEvent(new PerformEvent(true));
    }//GEN-LAST:event_buttonBrakeActionPerformed

    private void buttonFirstGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFirstGearActionPerformed

        GearState = 1;
    }//GEN-LAST:event_buttonFirstGearActionPerformed

    private void buttonStartTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartTripActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new events.TripEvent(true));

    }//GEN-LAST:event_buttonStartTripActionPerformed

    private void buttonSecondGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSecondGearActionPerformed
        GearState = 2;
    }//GEN-LAST:event_buttonSecondGearActionPerformed

    private void buttonThirdGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThirdGearActionPerformed
        GearState = 3;
    }//GEN-LAST:event_buttonThirdGearActionPerformed

    private void butonStopTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonStopTripActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new events.TripEvent(false));

    }//GEN-LAST:event_butonStopTripActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new events.Calibirator_state_reading(true));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Config.sendEvent(new events.Calibirator_state_reading(false));

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public LightBulb getTripbulb() {
        return Tripbulb;
    }

    public void setTripbulb(LightBulb Tripbulb) {
        this.Tripbulb = Tripbulb;
    }

    public LightBulb getClibirate_lightBulb() {
        return clibirate_lightBulb;
    }

    public void setClibirate_lightBulb(LightBulb clibirate_lightBulb) {
        this.clibirate_lightBulb = clibirate_lightBulb;
    }

    public LightBulb getCrusing_lightBulb1() {
        return crusing_lightBulb1;
    }

    public void setCrusing_lightBulb1(LightBulb crusing_lightBulb1) {
        this.crusing_lightBulb1 = crusing_lightBulb1;
    }

    public LightBulb getLightBulb3() {
        return lightBulb3;
    }

    public void setLightBulb3(LightBulb lightBulb3) {
        this.lightBulb3 = lightBulb3;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.lightbulb.LightBulb Tripbulb;
    private javax.swing.JButton butonStopTrip;
    private javax.swing.JToggleButton buttonAccelerate;
    private javax.swing.JButton buttonBrake;
    private javax.swing.JButton buttonFirstGear;
    private javax.swing.JButton buttonSecondGear;
    private javax.swing.JButton buttonSetFuel;
    private javax.swing.JToggleButton buttonStartCruise;
    private javax.swing.JButton buttonStartEngine;
    private javax.swing.JButton buttonStartTrip;
    private javax.swing.JButton buttonStopCruise;
    private javax.swing.JButton buttonStopEngine;
    private javax.swing.JButton buttonThirdGear;
    private eu.hansolo.lightbulb.LightBulb clibirate_lightBulb;
    private eu.hansolo.steelseries.gauges.Clock clock1;
    private eu.hansolo.lightbulb.LightBulb crusing_lightBulb1;
    private eu.hansolo.steelseries.gauges.DigitalRadial digitalRadial1;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayAvgFuel;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayCrusingSpeed;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayGear;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMaintenance;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayMilesDriven;
    private eu.hansolo.steelseries.gauges.DisplaySingle displayRPM;
    private eu.hansolo.steelseries.gauges.DisplayCircular driveshaft_display;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private eu.hansolo.lightbulb.LightBulb lightBulb1;
    private eu.hansolo.lightbulb.LightBulb lightBulb3;
    private org.pushingpixels.trident.ease.Linear linear1;
    private eu.hansolo.steelseries.gauges.Radial1Lcd radialFuel;
    private eu.hansolo.steelseries.gauges.Radial4 radialRPM;
    private eu.hansolo.steelseries.gauges.Radial2Lcd radialSpeedometer;
    private javax.swing.JTextArea screen;
    private javax.swing.JSlider sliderFuel;
    // End of variables declaration//GEN-END:variables
}
